# Generated by Django 3.2 on 2021-04-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField()),
                ('email_id', models.EmailField(max_length=100)),
                ('year_of_exp', models.IntegerField(default=True)),
                ('date_of_birth', models.DateField()),
                ('job_position', models.CharField(max_length=100)),
                ('annual_ctc', models.IntegerField(default=True)),
                ('skill_set', models.CharField(max_length=20)),
                ('preferred_location', models.CharField(max_length=20)),
                ('application_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
