# Generated by Django 3.2 on 2021-04-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210422_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_data',
            old_name='annual_ctc',
            new_name='current_ctc',
        ),
        migrations.AddField(
            model_name='employee_data',
            name='alternate_no',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='currently_serving',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='expected_ctc',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='employee_data',
            name='in_days',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='negotiable',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='reason_for_job_change',
            field=models.CharField(default='ntg', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='work_Location',
            field=models.CharField(default='chennai', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='skill_set',
            field=models.CharField(max_length=100),
        ),
    ]
