# Generated by Django 3.2 on 2021-04-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210422_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='currently_serving',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='email_id',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='job_position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='negotiable',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='preferred_location',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='reason_for_job_change',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='skill_set',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='work_Location',
            field=models.CharField(max_length=20),
        ),
    ]
