# Generated by Django 3.2 on 2021-04-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210422_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='current_company',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='status',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='in_days',
            field=models.CharField(max_length=10),
        ),
    ]
